const CartActionTypes = {
    ADD_ITEM: 'ADD_ITEM',
    INCREMENT_ITEM_QUANTITY: 'INCREMENT_ITEM_QUANTITY',
    DECREMENT_ITEM_QUANTITY: 'DECREMENT_ITEM_QUANTITY',
    REMOVE_ITEM: 'REMOVE_ITEM',
    UPDATE_NOTE: 'UPDATE_NOTE',
};

export default CartActionTypes;
